# Site settings
baseURL = "https://www.example.com"
languageCode = "en-us"
title = "Highlights"
theme = "hugo-highlights-theme"
googleAnalytics = "UA-XXXXXXX-Y"





[params]
  name = "Your Name"
  description = "Your Description"
  email = "your@mail.com"
  backgroundPerSection = true






  # header section
  [params.header]
    type = "header"
    title = "Highlights"
    description = "a fun little { responsive } single Pager by [HTML5 UP](//html5up.net)"
    buttonText = "begin"
    next = "about"






  # about section
  [[params.block]]
    id = "about"
    type = "text"
    title = "Who I Am"
    description = "Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum."
    next = "skills"
    picture = "pic01.jpg"






  # skill section
  [[params.block]]
    id = "skills"
    type = "list"
    title = "Stuff I do"
    description = "Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet vulputate."
    next = "infos"
    picture = "pic02.jpg"

    [[params.block.item]]
      icon = "icon solid major fa-camera-retro"
      title = "Magna Etiam"

    [[params.block.item]]
      icon = "icon solid major fa-pencil-alt"
      title = "Lorem Ipsum"

    [[params.block.item]]
      icon = "icon solid major fa-code"
      title = "Nulla Tempus"

    [[params.block.item]]
      icon = "icon solid major fa-coffee"
      title = "Sed Feugiat"






  # infos section
  [[params.block]]
    id = "infos"
    type = "text"
    title = "One more thing"
    description = "Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum."
    next = "footer"
    picture = "pic03.jpg"






  # footer section
  [params.footer]
    id = "footer"
    type = "footer"
    title = "Get in Touch"

    [params.footer.form]
      name = "Name"
      email = "Email"
      message = "Message"
      buttonText = "Send Message"

    [[params.footer.social]]
      title = "Twitter"
      icon = "icon brands alt fa-twitter"
      link = "#"
    [[params.footer.social]]
      title = "Facebook"
      icon = "icon brands alt fa-facebook-f"
      link = "#"
    [[params.footer.social]]
      title = "Instagramm"
      icon = "icon brands alt fa-instagram"
      link = "#"
    [[params.footer.social]]
      title = "Dribbble"
      icon = "icon brands alt fa-dribbble"
      link = "#"
    [[params.footer.social]]
      title = "Email"
      icon = "icon solid alt fa-envelope"
      link = "#"

    [[params.footer.copyright]]
      text = "© Untitled"
    [[params.footer.copyright]]
      text = "Design: [HTML5 UP](//html5up.net)"
    [[params.footer.copyright]]
      text = "Demo Images: [Unsplash](//unsplash.com/)"



